/*
 * Build-time sudoku puzzle bank generator.
 *
 * Generates puzzles with a guaranteed unique solution, then grades each one
 * with a human-technique solver so difficulty reflects the techniques a
 * player actually needs, not just the clue count:
 *
 *   easy   — naked/hidden singles only
 *   medium — also needs locked candidates or naked/hidden pairs
 *   hard   — also needs triples or X-wing
 *
 * Puzzles that cannot be finished with these techniques (chains/guessing
 * required) are rejected, so every shipped puzzle is solvable by pure logic.
 * The engine — tables, generator, uniqueness counter and the techniques —
 * lives in packages/shared/sudoku/solver.mjs.
 *
 * Usage: node tools/generate-puzzles.mjs   (writes src/puzzles.ts)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  countSolutions,
  generateSolved,
  grade,
  randInt,
  shuffle,
} from '../../shared/sudoku/solver.mjs';

const PER_DIFFICULTY = 100;

// --- digging (remove clues, keep uniqueness) ------------------------------

function digPuzzle(solution, targetRemovals) {
  const board = solution.slice();
  let removed = 0;
  for (const i of shuffle(Array.from({ length: 81 }, (_, k) => k))) {
    if (removed === targetRemovals) break;
    const saved = board[i];
    board[i] = 0;
    if (countSolutions(board) === 1) removed++;
    else board[i] = saved;
  }
  return board;
}

// --- main loop ------------------------------------------------------------

const buckets = { easy: [], medium: [], hard: [] };
const seen = new Set();
const LEVEL_TO_BUCKET = { 1: 'easy', 2: 'medium', 3: 'hard' };

const started = Date.now();
let attempts = 0;

while (Object.values(buckets).some((b) => b.length < PER_DIFFICULTY)) {
  attempts++;
  const needEasy = buckets.easy.length < PER_DIFFICULTY;
  const needHard = buckets.hard.length < PER_DIFFICULTY;
  // fewer removals lean easy, more lean hard
  const removals = needEasy && !needHard ? randInt(40, 47) : randInt(46, 58);

  const solution = generateSolved();
  const puzzle = digPuzzle(solution, removals);
  const level = grade(puzzle);
  const bucket = LEVEL_TO_BUCKET[level];
  if (!bucket || buckets[bucket].length >= PER_DIFFICULTY) continue;

  const str = puzzle.join('');
  if (seen.has(str)) continue;
  seen.add(str);
  buckets[bucket].push(str);

  if (attempts % 25 === 0 || Object.values(buckets).every((b) => b.length >= PER_DIFFICULTY)) {
    console.log(
      `attempt ${attempts}: easy ${buckets.easy.length} · medium ${buckets.medium.length} · hard ${buckets.hard.length} (${Math.round((Date.now() - started) / 1000)}s)`
    );
  }
}

// sort each bucket by clue count (desc) so puzzle #1 is the gentlest
for (const bucket of Object.values(buckets)) {
  bucket.sort((a, b) => clueCount(b) - clueCount(a));
}

function clueCount(str) {
  let n = 0;
  for (const ch of str) if (ch !== '0') n++;
  return n;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, '..', 'src', 'puzzles.ts');

const body = `// Generated by tools/generate-puzzles.mjs — do not edit by hand.
//
// Each puzzle is 81 chars, row-major, '0' for an empty cell. Every puzzle
// has a unique solution and is solvable with human techniques only:
// easy = singles, medium = + locked candidates & pairs, hard = + triples & X-wing.

export type Difficulty = "easy" | "medium" | "hard";

export const PUZZLES: Record<Difficulty, string[]> = {
${Object.entries(buckets)
  .map(
    ([name, list]) =>
      `\t${name}: [\n${list.map((p) => `\t\t"${p}",`).join('\n')}\n\t],`
  )
  .join('\n')}
};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, body);
console.log(
  `wrote ${outPath}: ${Object.entries(buckets)
    .map(([n, l]) => `${n} ${l.length}`)
    .join(', ')} (${attempts} attempts, ${Math.round((Date.now() - started) / 1000)}s)`
);
