/*
 * Games proved winnable at 4 suit(s), one bit per seed, seeds 1-0.
 *
 * Generated by tools/solve.mjs — do not edit. A placeholder until the first
 * scan of this suit count lands; see tools/solve.mjs.
 */

export const SCANNED = 0;

const BITS = "";

/** The seed behind each game number, in order — game #1 is GAMES[0]. */
export const GAMES: number[] = (() => {
	const bytes = atob(BITS);
	const games: number[] = [];
	for (let i = 0; i < SCANNED; i++) {
		if ((bytes.charCodeAt(i >> 3) >> (7 - (i & 7))) & 1) games.push(i + 1);
	}
	return games;
})();
