/*
 * Games proved winnable at 4 suit(s), one bit per seed, seeds 1-57.
 *
 * Generated by tools/solve.mjs — do not edit. Every bit set here means a
 * solution was found AND replayed through src/rules.ts, the module the game
 * itself plays by, ending with all eight runs carried off. So a game dealt
 * from this bank can always be finished. Seeds the search could not settle are
 * left out rather than guessed at, which is why this is smaller than the set
 * of games that are winnable in principle.
 *
 * Game numbers are positions in this list, so scanning further seeds only
 * appends and old numbers keep their cards. Widening the search instead would
 * prove seeds that were skipped before and shift every number after them, which
 * would quietly repoint everybody's saved games — so the search settings are
 * part of the bank, not a knob to turn later.
 */

export const SCANNED = 57;

const BITS =
	"/f3+vnk9/4A=";

/** The seed behind each game number, in order — game #1 is GAMES[0]. */
export const GAMES: number[] = (() => {
	const bytes = atob(BITS);
	const games: number[] = [];
	for (let i = 0; i < SCANNED; i++) {
		if ((bytes.charCodeAt(i >> 3) >> (7 - (i & 7))) & 1) games.push(i + 1);
	}
	return games;
})();
