/*
 * Build-time dictionary generator.
 *
 * One list serves as both the words the game accepts and the words it counts
 * towards a puzzle's total, so it comes from ESDB size 35 ("small"): the
 * words an ordinary speaker recognises. A wider tier would make every total
 * unreachable for anyone without a crossword habit.
 *
 * Only words that can ever be played are kept: four letters or more, at most
 * seven distinct letters, and no S — the puzzles never contain one, or every
 * plural would be a free word. Slurs and crude words go too; in this game a
 * word that is not in the list simply does not count.
 *
 * The generated file is committed — re-run this only to refresh the list.
 *
 * Usage: node tools/build-words.mjs   (writes src/words.ts)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CRUDE, ESDB_LICENCE, SLURS, loadTier } from "../../shared/words/esdb.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TIER = 35;
const MIN_LENGTH = 4;
const HIVE_SIZE = 7;

async function main() {
	const tier = await loadTier(TIER);
	const words = tier
		.filter((w) => w.length >= MIN_LENGTH && !w.includes("s") && new Set(w).size <= HIVE_SIZE)
		.filter((w) => !SLURS.has(w) && !CRUDE.has(w))
		.sort();
	const pangrams = words.filter((w) => new Set(w).size === HIVE_SIZE);
	const sets = new Set(pangrams.map((w) => [...new Set(w)].sort().join("")));

	const body = `// Generated by tools/build-words.mjs — do not edit by hand.
//
// Word list derived from the English Speller Database (ESDB, previously
// SCOWL) at https://wordlist.aspell.net — size ${TIER}, US spelling.
//
${ESDB_LICENCE}

// Sorted, one word per line. Every word is ${MIN_LENGTH}+ letters, has at most
// ${HIVE_SIZE} distinct letters and no S; ${pangrams.length} of them use exactly ${HIVE_SIZE}, across
// ${sets.size} letter sets, and those are where the puzzles come from.
export const WORDS = \`${words.join("\n")}\`;
`;
	const file = path.join(ROOT, "src", "words.ts");
	fs.writeFileSync(file, body);
	console.log(
		`\n${words.length} words (${tier.length - words.length} dropped from tier ${TIER}), ` +
			`${pangrams.length} pangrams over ${sets.size} letter sets  →  ${path.relative(ROOT, file)}`
	);
}

main();
