/*
 * Build-time 24 Game hand bank generator.
 *
 * A hand is four numbers from 1 to 13 — the ranks of a deck — and the bank is
 * every hand that can make 24 at all: 1,820 hands can be dealt and 1,362 of
 * them work. Each is solved by src/solve.ts, the same module the game uses to
 * show a solution, and graded by how many ways there are to do it without
 * ever passing through a fraction: plenty of those routes is easy, a few is
 * medium, and two or fewer — including the sixteen hands that cannot be done
 * in whole numbers at all — is hard. Within a bucket, hands are ordered
 * most-routes first, so #1 is the gentlest.
 *
 * Usage: node tools/generate-puzzles.mjs   (writes src/puzzles.ts)
 * Needs a Node that strips TypeScript on import (22.18 or later).
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { frac, solutions } from '../src/solve.ts';

const MAX_RANK = 13;
const EASY_ROUTES = 10; // whole-number routes at or above this count: easy
const HARD_ROUTES = 2; // whole-number routes at or below this count: hard

const hands = [];
for (let a = 1; a <= MAX_RANK; a++) {
  for (let b = a; b <= MAX_RANK; b++) {
    for (let c = b; c <= MAX_RANK; c++) {
      for (let d = c; d <= MAX_RANK; d++) {
        const cards = [a, b, c, d];
        const found = solutions(cards.map((n) => frac(n)));
        if (!found.length) continue;
        const whole = found.filter((s) => s.ints).length;
        let bucket = 'medium';
        if (whole <= HARD_ROUTES) bucket = 'hard';
        else if (whole >= EASY_ROUTES) bucket = 'easy';
        hands.push({ cards, routes: found.length, whole, bucket });
      }
    }
  }
}

const banks = { easy: [], medium: [], hard: [] };
for (const hand of hands) banks[hand.bucket].push(hand);
for (const bank of Object.values(banks)) {
  bank.sort((x, y) => y.whole - x.whole || y.routes - x.routes);
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, '..', 'src', 'puzzles.ts');

const body = `// Generated by tools/generate-puzzles.mjs — do not edit by hand.
//
// Every hand of four cards, 1 to 13, that can make 24, graded by how many
// ways there are to do it and whether any of them stays in whole numbers.
// Within each bucket the hands with the most whole-number routes come first.

export type Difficulty = "easy" | "medium" | "hard";

export const PUZZLES: Record<Difficulty, number[][]> = {
${Object.entries(banks)
  .map(
    ([name, bank]) =>
      `\t${name}: [\n${bank.map((h) => `\t\t[${h.cards.join(', ')}],`).join('\n')}\n\t],`
  )
  .join('\n')}
};
`;

fs.writeFileSync(outPath, body);
console.log(
  `wrote ${outPath}: ${Object.entries(banks)
    .map(([n, b]) => `${n} ${b.length}`)
    .join(', ')} of ${hands.length} solvable hands`
);
