// Position data: the index (ratings only) and lazily fetched chunks, plus the
// two ways of picking from it — a random position for quick play and the
// date-seeded ten for the daily set. Files are generated by
// tools/build-positions.mjs.

export type EngineScore = number | string; // centipawns, or "M3" / "M-2" for mate in n

export interface Position {
	id: string;
	fen: string;
	/** The opponent's move that led here, UCI; highlighted on the board. */
	last: string;
	rating: number;
	themes: string[];
	/** Every legal move with its score for the side to move, best first. */
	moves: [string, EngineScore][];
	/** Best line in UCI, starting with the best move. */
	pv: string[];
}

export interface Index {
	count: number;
	chunkSize: number;
	depth: number;
	ratings: number[];
}

export type Difficulty = "any" | "easy" | "medium" | "hard";

// Keep in sync with BANDS in tools/build-positions.mjs.
export const BANDS: Record<Exclude<Difficulty, "any">, { min: number; max: number; label: string }> = {
	easy: { min: 0, max: 1199, label: "Easy" },
	medium: { min: 1200, max: 1799, label: "Medium" },
	hard: { min: 1800, max: 9999, label: "Hard" },
};

export const DAILY_COUNT = 10;
// The daily ten: three easy, four medium, three hard, sorted by rating.
const DAILY_MIX: Exclude<Difficulty, "any">[] = [
	"easy", "easy", "easy",
	"medium", "medium", "medium", "medium",
	"hard", "hard", "hard",
];

const BASE = `${import.meta.env.BASE_URL}positions/`;
const chunks = new Map<number, Promise<Position[]>>();

export async function loadIndex(): Promise<Index> {
	const res = await fetch(`${BASE}index.json`);
	if (!res.ok) throw new Error(`positions index: ${res.status}`);
	return res.json();
}

export function loadPosition(index: Index, i: number): Promise<Position> {
	const c = Math.floor(i / index.chunkSize);
	let chunk = chunks.get(c);
	if (!chunk) {
		chunk = fetch(`${BASE}c${String(c).padStart(3, "0")}.json`).then((r) => {
			if (!r.ok) throw new Error(`positions chunk ${c}: ${r.status}`);
			return r.json();
		});
		chunks.set(c, chunk);
	}
	return chunk.then((list) => list[i % index.chunkSize]);
}

export function difficultyOf(rating: number): Exclude<Difficulty, "any"> {
	if (rating <= BANDS.easy.max) return "easy";
	if (rating <= BANDS.medium.max) return "medium";
	return "hard";
}

function inBand(rating: number, d: Difficulty): boolean {
	return d === "any" || (rating >= BANDS[d].min && rating <= BANDS[d].max);
}

/**
 * A random position index in the band, preferring ones not in `seen`. When
 * every candidate has been seen the whole band is eligible again.
 */
export function pickRandom(index: Index, difficulty: Difficulty, seen: Set<number>): number {
	const all: number[] = [];
	for (let i = 0; i < index.count; i++) if (inBand(index.ratings[i], difficulty)) all.push(i);
	const fresh = all.filter((i) => !seen.has(i));
	const pool = fresh.length > 0 ? fresh : all;
	return pool[Math.floor(Math.random() * pool.length)];
}

// --- daily ---

/** Local calendar date as YYYY-MM-DD: the daily set rolls over at midnight local time. */
export function todayKey(d = new Date()): string {
	const y = d.getFullYear();
	const m = String(d.getMonth() + 1).padStart(2, "0");
	const day = String(d.getDate()).padStart(2, "0");
	return `${y}-${m}-${day}`;
}

export function yesterdayKey(d = new Date()): string {
	const y = new Date(d);
	y.setDate(y.getDate() - 1);
	return todayKey(y);
}

// mulberry32, seeded from the date string
function seededRandom(seed: string): () => number {
	let h = 1779033703 ^ seed.length;
	for (let i = 0; i < seed.length; i++) {
		h = Math.imul(h ^ seed.charCodeAt(i), 3432918353);
		h = (h << 13) | (h >>> 19);
	}
	let a = h >>> 0;
	return () => {
		a = (a + 0x6d2b79f5) >>> 0;
		let t = a;
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

/** The ten position indices for a given day, easiest first. */
export function pickDaily(index: Index, dateKey: string): number[] {
	const rand = seededRandom(`passant:${dateKey}`);
	const byBand: Record<string, number[]> = { easy: [], medium: [], hard: [] };
	for (let i = 0; i < index.count; i++) byBand[difficultyOf(index.ratings[i])].push(i);
	const taken = new Set<number>();
	const picks: number[] = [];
	for (const band of DAILY_MIX) {
		const pool = byBand[band].filter((i) => !taken.has(i));
		if (pool.length === 0) continue;
		const i = pool[Math.floor(rand() * pool.length)];
		taken.add(i);
		picks.push(i);
	}
	return picks.sort((a, b) => index.ratings[a] - index.ratings[b]);
}
