/*
 * Games proved winnable, one bit per seed, seeds 1-3396.
 *
 * Generated by tools/solve.mjs — do not edit. Every bit set here means a
 * solution was found AND replayed through src/rules.ts, the module the game
 * itself plays by, ending with all four foundations full. So a game dealt from
 * this bank can always be finished. Seeds the search could not settle are left
 * out rather than guessed at, which is why this is smaller than the set of
 * games that are winnable in principle.
 *
 * Judged at draw three, which a draw-one game can always replay — three single
 * draws land the same cards on the waste in the same order — so both modes are
 * covered — and tools/solve.mjs --check-draws tests that rather than asserting it.
 *
 * Game numbers are positions in this list, so scanning further seeds only
 * appends and old numbers keep their cards. Widening the search instead would
 * prove seeds that were skipped before and shift every number after them, which
 * would quietly repoint everybody's saved games — so the search settings are
 * part of the bank, not a knob to turn later.
 */

export const SCANNED = 3396;

const BITS =
	"p9+N1LNfl77aa1b2q1x/vbbd8PHHP+83ft823vlTmz39/y2RvO/7+r/e9e/f0ev/653v7/Pr9vXWW7/aX955VfH2VjX/erzvemzl" +
	"P+lu9y5rb/OZ7/6u/W1Xu73+3vo98l/6XyX9yj3P39dV42zPFee/XDhNt916t2vf8Jb+96/9/7/3Lt/+9nrDnfd6Ojvvi////FEX" +
	"X8/HY3AEfufbnNfvzmjrNFmmm23//Ew329P7z/S+dTmnN+6fX/9s/ztos47Lm6Yn9UgfvnhU7fa5JPX73jvd8ub77V+e1lrlNflv" +
	"r/6K/T/t3R58SP/675C9HadNfz1//m/8jR19z/s/blz7qzvb55rj6fp/dzjH6rfOt/evfX/7+1/hL/6tx1e3/cI7/U+nv1nmvv9/" +
	"dV2f+x9b/5Hs1x+pd/nv68SDY9+8/f1rnt7Wtb1K7yt/lJ/LtcrTXy84P/uriTf/Es4bz5yYGdswV242m1M3SK9l5h8m8ek3u9bj" +
	"/Lw9WV97Pd391/+Wnd/n6v/L5Ou28HPLz3Nf3jbG3MH3cbvvW6f/B29na2/vfOu7P5A=";

/** The seed behind each game number, in order — game #1 is GAMES[0]. */
export const GAMES: number[] = (() => {
	const bytes = atob(BITS);
	const games: number[] = [];
	for (let i = 0; i < SCANNED; i++) {
		if ((bytes.charCodeAt(i >> 3) >> (7 - (i & 7))) & 1) games.push(i + 1);
	}
	return games;
})();
